### ISSUE TITLE
Command exec error

### ISSUE THREAD

**Issue by maorhz** [pcgeek86/aws-powershell-container#1]
>docker run --rm --interactive --tty --mount "src=$HOME/.aws/,dst=/root/.aws/,type=bind" ghcr.io/pcgeek86/aws-powershell-container:4.1.17.0
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/mobaxterm/.aws.
See 'docker run --help'.

I'm running Docker Desktop 20.10.12 on my Windows 10 machine

**Comment by pcgeek86** [comment]
@maorhz In order to use this, you'll need to set your AWS credentials according to the AWS documentation. The standard file location for these credentials is under `$HOME/.aws/credentials`.
